steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/skeletonauthanddb:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/skeletonauthanddb:$BUILD_ID']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'skeletonauthanddb'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/skeletonauthanddb:$BUILD_ID'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/skeletonauthanddb:$BUILD_ID'
