mutation CreateUserData($contentText: String!, $createUserId: String!, $updateUserId: String!) @auth(level: USER) {
  userData_insert(data: {contentText: $contentText, createUserId: $createUserId, createTS_expr: "request.time", updateUserId: $updateUserId, updateTS_expr: "request.time", user: {id_expr: "auth.uid"}})
}

mutation UpdateUserData($id: UUID!, $contentText: String!, $updateUserId: String!) @auth(level: USER) {
  userData_update(key: {id: $id}, data: {contentText: $contentText, updateUserId: $updateUserId, updateTS_expr: "request.time"})
}

mutation DeleteUserData($id: UUID!) @auth(level: USER) {
  userData_delete(key: {id: $id})
}

query ListUserData @auth(level: USER) {
  userDatas(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    contentText
    createTS
    updateTS
  }
}